### ISSUE TITLE
Remove the YunoHost panel overlay because it breaks Google AMP support?

### ISSUE THREAD

**Issue by badrihippo** [YunoHost-Apps/ghost_ynh#100]
### Describe the bug

When deploying Ghost, the YunoHost overlay is injected into the code via nginx. This makes Google Search Console throws an error saying "AMP issues detected" and that external CSS and JS are not allowed. Because of this, Google refuses to include my website in their AMP (Accelerated Mobile Pages) search results.

### Context

- Hardware: *VPS rented from [HelioHost](https://heliohost.org)*
- YunoHost version: 4.3.5
- I have access to my server: *Through SSH and the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: **master/4.32.1~ynh1**
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce

- Deploy Ghost as a public website
- Register your website on Google Search Console
- After some time, you will receive an email from Google describing the AMP issues.

Quote from and screenshot of the Google email:

>  External stylesheets are not supported, except for allowed font providers. Use the document inline 'style amp-custom' tag instead.
>
> Custom JavaScript is not allowed.

![AMP issues](https://user-images.githubusercontent.com/7288084/148776096-d22cbb8d-4474-42e9-8c7e-6e4f2c055f75.png)

Since Ghost has AMP support (as far as I know), I'm guessing the culprits are the YunoHost CSS and JS injected later. (I am testing it right now to figure it out). If that is the case, we should comment out the `include` overlay line in Ghost's `nginx.conf` to prevent the errors from appearing. (Or perhaps make it a toggle in the settings? That might be more complicated though).

**Comment by tituspijean** [comment]
You have a global setting to remove the panel overlay in apps (`yunohost settings set ssowat.panel_overlay.enabled -v False`), but you can indeed remove the `include` line too, but you may lose this setting upon each app upgrade.

Considering the serious threat AMP imposes on the web (e.g. [Why AMP is bad for your site and for the Web](https://medium.com/@danbuben/why-amp-is-bad-for-your-site-and-for-the-web-e4d060a4ff31)), I am tagging this as `won't solve`.

**Comment by badrihippo** [comment]
Oh wow, I did not know that was the backstory of AMP :open_mouth:

Given that we're consciously doing things like self-hosting and using GoatCounter and Commento, I suppose we should just disable AMP altogether.

Thanks for the tip about the panel overlay though! :slightly_smiling_face:
