### ISSUE TITLE
Can't upload image

### ISSUE THREAD

**Issue by kazukyakayashi** [YunoHost-Apps/ghost_ynh#112]
### Describe the bug

When I try to upload an image, for an article, change the avatar or other, I get an error message from Ghost.

Note: I don't get any error when uploading themes.

![firefox_wFaYBUYfFX](https://user-images.githubusercontent.com/39823221/152632415-baed23a3-c5b5-4299-9688-d185883f21f7.png)

### Context

- Hardware: Kimsufi KS-1 
- YunoHost version: 4.3.6.2 (stable)
- Ghost 4.32.1
- I have access to my server: Through SSH | through the webadmin

### Logs

I don't know where to look with Yunohost.

**Comment by tituspijean** [comment]
> I don't know where to look with Yunohost.

Webadmin > Services > `ghost` service, and `Share with YunoPaste`.

**Comment by kazukyakayashi** [comment]
Log : [YunoPast](https://paste.yunohost.org/patezuweci)

Output for `ls -la /var/www/ghost/content/`
```
ls -la /var/www/ghost/content/
total 36
drwxr-x--- 9 ghost www-data 4096 Jan  7 16:05 .
drwxr-x--- 9 ghost www-data 4096 Feb  3 07:47 ..
drwxr-x--- 2 ghost www-data 4096 Jan  7 16:05 adapters
drwxr-x--- 2 ghost www-data 4096 Feb  3 07:48 data
drwxr-x--- 2 ghost www-data 4096 Jan  7 16:05 images
drwxr-x--- 2 ghost www-data 4096 Feb  5 00:00 logs
drwxr-x--- 2 ghost www-data 4096 Feb  5 07:59 public
drwxr-x--- 2 ghost www-data 4096 Feb  3 07:52 settings
drwxr-x--- 4 ghost www-data 4096 Feb  3 08:02 themes
```

**Comment by tituspijean** [comment]
Can you try uploading an image, and share the log again? Have a look to your browser's console too (F12), to see if there are any errors in there.

**Comment by kazukyakayashi** [comment]
➡️ https://paste.yunohost.org/necuyumuge

With the Firefox console I get an error 502
![firefox_OAPm5Jj5aj](https://user-images.githubusercontent.com/39823221/152674508-86d19405-344b-4558-b628-559d6494f28d.png)

**Comment by tituspijean** [comment]
Weirdly the error does not show up in the service log... 

There are the following lines twice in the log. Did you manually stop the service, or do the times correspond to when you tried to upload the images?

> Feb 06 09:01:17 systemd[1]: ghost.service: Main process exited, code=killed, status=4/ILL
Feb 06 09:01:17 systemd[1]: ghost.service: Failed with result 'signal'.

I'm a bit at a loss here.

1. Can you try force upgrading the app? `sudo yunohost app upgrade ghost -F`
2. If that does not fix the issue, try making the log more verbose: `sudo nano +23 /var/www/ghost/config.production.json`. There, change `"level": "info"` to `"level": "debug"`, restart the service, try uploading again and have a look to the logs.

**Comment by kazukyakayashi** [comment]
Ghost restarts every time I try to upload an image, I don't understand either.

- I tried `sudo yunohost app upgrade ghost -F` but it does not change anything.

- With `"level": "debug"` ... ...
➡️ https://paste.yunohost.org/narotikape

- I reinstalled Ghost but same thing, impossible to upload images.

**Comment by gcmtnskr** [comment]
@kazukyakayashi has this issue been solved? and can we close this 'issue' if so.

**Comment by kazukyakayashi** [comment]
Hello
Unfortunately no the problem was not solved, so I switched to Wordpress.
