### ISSUE TITLE
Issue with ghost service

### ISSUE THREAD

**Issue by sovereignhodler** [YunoHost-Apps/ghost_ynh#122]
### Describe the bug

*Ghost does not run.*

### Context

- Hardware: *VPS with debian 10*
- YunoHost version: 4.3.6.2
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app install https://github.com/YunoHost-Apps/gho                                                                   st_ynh
    ```

### Expected behavior

*Should run*

### Logs

> Mar 04 11:11:06 systemd[1]: Started ghost systemd service.
> Mar 04 11:11:06 node[1623]: [2022-03-04 11:11:06] INFO Ghost is running in production...
> Mar 04 11:11:06 node[1623]: [2022-03-04 11:11:06] INFO Your site is now available on https://domain
> Mar 04 11:11:06 node[1623]: [2022-03-04 11:11:06] INFO Ctrl+C to shut down
> Mar 04 11:11:06 node[1623]: [2022-03-04 11:11:06] INFO Ghost server started in 0.36s
> Mar 04 11:11:06 node[1623]: [2022-03-04 11:11:06] WARN Database state requires initialisation.
> Mar 04 11:11:07 node[1623]: [2022-03-04 11:11:07] ERROR The server has encountered an error.
> Mar 04 11:11:07 node[1623]: 
> Mar 04 11:11:07 node[1623]: The server has encountered an error.
> Mar 04 11:11:07 node[1623]: {"name":"1-create-tables.js"}
> Mar 04 11:11:07 node[1623]: "Error occurred while executing the following migration: 1-create-tables.js"
> Mar 04 11:11:07 node[1623]: Error ID:
> Mar 04 11:11:07 node[1623]:     300
> Mar 04 11:11:07 node[1623]: ----------------------------------------
> Mar 04 11:11:07 node[1623]: MigrationScriptError: The server has encountered an error.
> Mar 04 11:11:07 node[1623]:     at DatabaseStateManager.makeReady (/var/www/ghost/core/server/data/db/state-manager.js:95:32)
> Mar 04 11:11:07 node[1623]:     at MigrationScriptError.KnexMigrateError (/var/www/ghost/node_modules/knex-migrator/lib/errors.js:7:26)
> Mar 04 11:11:07 node[1623]:     at new MigrationScriptError (/var/www/ghost/node_modules/knex-migrator/lib/errors.js:25:26)
> Mar 04 11:11:07 node[1623]:     at /var/www/ghost/node_modules/knex-migrator/lib/index.js:1032:19
> Mar 04 11:11:07 node[1623]: Error: No support for database client mysql2
> Mar 04 11:11:07 node[1623]:     at MigrationScriptError.IgnitionError (/var/www/ghost/node_modules/ghost-ignition/lib/errors/index.js:63:27)
> Mar 04 11:11:07 node[1623]:     at MigrationScriptError.KnexMigrateError (/var/www/ghost/node_modules/knex-migrator/lib/errors.js:7:26)
> Mar 04 11:11:07 node[1623]:     at new MigrationScriptError (/var/www/ghost/node_modules/knex-migrator/lib/errors.js:25:26)
> Mar 04 11:11:07 node[1623]:     at /var/www/ghost/node_modules/knex-migrator/lib/index.js:1032:19
> Mar 04 11:11:07 node[1623]: 
> Mar 04 11:11:07 node[1623]: [2022-03-04 11:11:07] WARN Ghost is shutting down
> Mar 04 11:11:07 node[1623]: [2022-03-04 11:11:07] WARN Ghost has shut down
> Mar 04 11:11:07 node[1623]: [2022-03-04 11:11:07] WARN Your site is now offline
> Mar 04 11:11:07 node[1623]: [2022-03-04 11:11:07] WARN Ghost was running for a few seconds
> Mar 04 11:11:07 systemd[1]: ghost.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
> Mar 04 11:11:07 systemd[1]: ghost.service: Failed with result 'exit-code'.
> Mar 04 11:11:07 systemd[1]: ghost.service: Service RestartSec=100ms expired, scheduling restart.
> Mar 04 11:11:07 systemd[1]: ghost.service: Scheduled restart job, restart counter is at 5.
> Mar 04 11:11:07 systemd[1]: Stopped ghost systemd service.
> Mar 04 11:11:07 systemd[1]: ghost.service: Start request repeated too quickly.
> Mar 04 11:11:07 systemd[1]: ghost.service: Failed with result 'exit-code'.
> Mar 04 11:11:07 systemd[1]: Failed to start ghost systemd service.

**Comment by tituspijean** [comment]
Can you provide the link to full log shared with YunoPaste?

**Comment by sovereignhodler** [comment]
https://paste.yunohost.org/ucanuvibev

**Comment by tituspijean** [comment]
Can you share the installation attempt log?

**Comment by sovereignhodler** [comment]
> Can you share the installation attempt log?

https://paste.yunohost.org/raw/aqorafemin

**Comment by ppnplus** [comment]
I’m having the same issue, too. I installed on the subdirectory (domain .tld/blog).

**Comment by scharfsinn** [comment]
I´have the the same issue, ghost can not be installed

[https://paste.yunohost.org/raw/ugefibuwit](url)

**Comment by JesperBllnbm** [comment]
Same problem here 😭
I even can't manage to paste my log. It should be done with `sudo yunohost app install https://github.com/YunoHost-Apps/ghost_ynh | /usr/bin/yunopaste`, right?

**Comment by tituspijean** [comment]
If you read the text at the bottom of the install attempt, there is the command to share the log. It stars with `yunohost log share ...`. Anyways, I guess we have enough logs now.

**Comment by sovereignhodler** [comment]
It's fixed. Thanks

**Comment by tituspijean** [comment]
(Dont thank me, I merely kept up with the latest update. 😅 They may have fixed the bug upstream. 🙂)

**Comment by sovereignhodler** [comment]
It's failing again.

https://paste.yunohost.org/raw/ezokevekof
