### ISSUE TITLE
Version 5.0 Is missing? 

### ISSUE THREAD

**Issue by gcmtnskr** [YunoHost-Apps/ghost_ynh#163]
### Describe the bug

*5.2.2~ynh1 of GHOST is still on the v4.48.0*

### Context

- Hardware: *Linode Server*
- YunoHost version: 4.3.6.3 (stable)
- I have access to my server: *Through SSH & through the webadmin *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 5.2.2~ynh1

### Steps to reproduce

- *If the error occurs in your browser, explain what you did:*
   1. *Go to Yunohost Admin page, then to  Applications, find 'Ghost', and Install* & or *Go to System Update, Upgrade Ghost 4.48.0 (your current Version) to 5.2.2*
   3. *Go to Ghost Admin page, sign up/sign in and proceed into Admin Dashboard*
   4. *Top of screen has a error alert that you are not on Ghost 5.0*
   5. *Looking for new 5.0 features that did not exist in previous versions and are missing in 5.2.2, such as NEW DASHBOARD.

### Attempts to solve (ALL FAILED)

1. Restart Server from Yunohost panel 
2. Install a new Ghost instance
3. Upgrade Primary Ghost instance
4. Upgrade Pre-production Ghost Instance

### Expected behavior

*Upgrade/Install to Ghost 5.2.2 and expect to see the new admin dashboard featured in Version 5.0, as well as other features like multiple newsletters.*

### Logs

5.48 TO 5.2.2 LOG (https://paste.yunohost.org/raw/fafirakece)

NEW INSTALLATION LOG https://paste.yunohost.org/raw/legabazoso

**Comment by tituspijean** [comment]
Thank you for the report! Indeed there's an issue with our script that monitors the new releases from Ghost. I'll try to fix it tomorrow.

Cause: Ghost stopped including an asset file with their releases. We now need to download the zipball of the source code.

**Comment by gcmtnskr** [comment]
any idea of a timeline on the next fix? Security Alert seems to be concerning, looking forward to it.

**Comment by badrihippo** [comment]
Seconded. If this is going to take a while, how about upgrading to the latest 4.x version in the meantime so at least the security hole is patched?

**Comment by AbsqueHabitatore** [comment]
Any reasonable way to upgrade manually? Having problems with the CLI.

**Comment by tituspijean** [comment]
> Seconded. If this is going to take a while, how about upgrading to the latest 4.x version in the meantime so at least the security hole is patched?

Patched version does not include the built app any more so... we need to build everything. I have yet to find the time and how to build the webadmin.

> Any reasonable way to upgrade manually? Having problems with the CLI.

No idea.

**Comment by badrihippo** [comment]
I've taken a shot at fixing this with pull request #175. The install process is working, but I still have to test the backup/restore and upgrade processes.

@gcmtnskr @AbsqueHabitatore @scriptor-pro would any of you be willing to do a test run? Please note that it's currently **unsafe** so don't try this on your production blog, but if you could install a fresh Ghost specially for testing and let me know whether it works, that would be great.

**Comment by scriptor-pro** [comment]
I'm in

**Comment by badrihippo** [comment]
@scriptor-pro thanks but it's already been tested and merged in now! Upgrade and enjoy your new Ghost :wink:
