### ISSUE TITLE
[BUG] Installation impossible due to SQL error?

### ISSUE THREAD

**Issue by SangeloDev** [YunoHost-Apps/ghost_ynh#169]
### Describe the bug

Installation impossible due to SQL error as far as I can see. When trying to install ghost on a domain that has nothing installed on it, it just fails.

### Context

- **Hardware:** VPS bought online
- **YunoHost version:** 11.0.7 (testing)
- **I have access to my server:** Through SSH & through the webadmin
- **Are you in a special context or did you perform some particular tweaking on your YunoHost instance?:** yes
  - **If yes, please explain:** I have modified the MySQL password without knowing that it may break things. I have since changed it back to no password and everything has been working fine. I don't know weather this is something to consider, though I thought I could also mention this
- **Using, or trying to install package version/branch:** master & testing

### Steps to reproduce

```sh
sudo yunohost app install https://github.com/YunoHost-Apps/ghost_ynh/tree/testing
```

### Logs

https://paste.yunohost.org/raw/aqusunuyuc

**Comment by tituspijean** [comment]
Issue is unrelated to Ghost. Closing, but we can keep chatting here to help you solve the issue.

**Comment by SangeloDev** [comment]
Thanks for pointing that out, apparently I was heading in a wrong direction while trying to understand the logs. I fixed it by removing the repository, as I didn't really need it anymore. Thanks for helping out!
