### ISSUE TITLE
ghost 

### ISSUE THREAD

**Issue by scriptor-pro** [YunoHost-Apps/ghost_ynh#172]
Upon installing Ghost I noticed some kind of pop-up linking to this https://github.com/TryGhost/Ghost/security/advisories/GHSA-7v28-g2pq-ggg8 and recommending an upgrade to 5.2.3 as soon as possible

Does YNH have plan to provide the 5.2.3 upgrade ? 

Thanks in advance !

**Comment by tituspijean** [comment]
See #163.
