### ISSUE TITLE
Using the official Ghost CLI to manage installations

### ISSUE THREAD

**Issue by badrihippo** [YunoHost-Apps/ghost_ynh#176]
I had brought this up earlier in #164: Basically, we're currently manually setting up Ghosts by sort-of following their [install from source](https://ghost.org/docs/install/source/) instructions, which are more geared towards *developing* Ghost, not running it. Instead of that I thought it'd make more sense to use the official command-line tool, `@tryghost/cli` tool which is especially designed for running and managing Ghost instances.

My original idea was to write up some logic and install `@tryghost/cli` for the first instance, then use the existing installation to manage subsequent instances. That might prove to be complicated, though (especially if one of the apps is being backed up or uninstalled!) so now I'm instead considering a `@tryghost/cli` for each Ghost installation?

@tituspijean mentioned that the Ghost CLI complains when trying to transition from a manually installed edition one managed by the tool, so that's one thing to figure out first—perhaps by installing Ghost freshly and then moving in parts of the old `content` directory. We'd also have to investigate how conducive the CLI is to being run as part of a script at all (rather than being called manually).

I'll probably start work on this at some point; hence creating this issue to track discussion/updates until I make a pull request :wink:

**Comment by sylvain441** [comment]
Hi there, thank you for your message.
I'm not a hardcore system admnistrator (i don't like this).

I'm trying to find a way to upgrade my ghost website to 5.0.
I did an update through YunoHost UI 
That was successful operation apart from the fact that my ghost instance was not updated at all... (still running under 4.40).

Next : i tried to find my way through command line, installed ghost-cli ...
www-data user permission is pulling my hair off.

My question may seem very simple : does updating ghost with yunohost also updates all it's instances ?
Thx in advance

**Comment by badrihippo** [comment]
@sylvain441 before I answer your question: there was a problem with the upgrade from 4.x to 5.x because Ghost changed the way their files were structured, so we had to change things on our end too (see #163). Perhaps that's why you couldn't upgrade either?

All that got fixed with [yesterday's commit](https://github.com/YunoHost-Apps/ghost_ynh/commit/67eff99fccc946a7d3d981fc89f7ee8c31b19f5e), so if you try upgrading again now I think you'll find yourself on 5.x. If it doesn't work please file a separate issue (since it's not directly related to what I'm discussing here) and I'll be happy to help you out there :slightly_smiling_face:

(And to answer your question: in YunoHost we are upgrading the Ghost instances manually; that's literally the only thing being upgraded. So yes, if you upgrade to version X.XX you should technically end up with a running X.XX website when you're done; it's just that there was a bit of a slip up in this case!)

**Comment by sylvain441** [comment]
Thank you for your answer.
I did the update with the new commit and it seems to work
Thank you again and sorry for messing up your issue with an unrelevant question

**Comment by tituspijean** [comment]
Hi @badrihippo, I have finally managed to switch to Ghost CLI in the following PR: https://github.com/YunoHost-Apps/ghost_ynh/pull/228

It would be great to test it and give some feedback!

`sudo yunohost app upgrade -u https://github.com/YunoHost-Apps/ghost_ynh/tree/fix -F`

**Comment by badrihippo** [comment]
Oh nice! I'm travelling right now but I will definitely see it in the next couple of days; in fact one of my friends wanted to test run Ghost so I can let that double up as the test!
