### ISSUE TITLE
Consider keeping only productions assets

### ISSUE THREAD

**Issue by nicofrand** [YunoHost-Apps/ghost_ynh#193]
### Describe the bug

Not a bug per se but the installation takes quite a lot of space:

* `node_modules` takes already 1.2G.
* `.cache/yarn` takes 1.1G

I have a really limited disk space on my VPS and this is quite a lot.

During the installation all the dependencies (dev & prod) are installed, to be able to build the app (`yarn build`) and then run it.

Removing dev dependencies once the build step is finished would avoid some unused assets.

I believe this would be possible by adding the steps below in https://github.com/YunoHost-Apps/ghost_ynh/blob/master/scripts/install#L142-L147:

0. `rm .cache/yarn/* -rf`
0. `rm node_modules -rf`
0. `yarn install --production`

This basically removes the dependencies and reinstall the project in production.

### Context

- Hardware: *VPS bought online.*
- YunoHost version: x.x.x

**Comment by tituspijean** [comment]
Hi @nicofrand, I have finally managed to switch to Ghost CLI in the following PR: https://github.com/YunoHost-Apps/ghost_ynh/pull/228 This seems to minimize the disk usage. :)

It would be great to test it and give some feedback!

`sudo yunohost app upgrade -u https://github.com/YunoHost-Apps/ghost_ynh/tree/fix -F`

**Comment by nicofrand** [comment]
There is a 300 mb difference with the previous installation:

```
root@nicofrand:/var/www# du -sh ./*
1.3G    ./ghost
1.6G    ./ghost.bak
root@nicofrand:/var/www# du -sh ./ghost/*
596M    ./ghost/ghost
97M     ./ghost/node_modules
4.0K    ./ghost/package.json
184K    ./ghost/package-lock.json
root@nicofrand:/var/www# du -sh ./ghost.bak/*
12K     ./ghost.bak/content
364M    ./ghost.bak/ghost
4.0K    ./ghost.bak/LICENSE
1.3G    ./ghost.bak/node_modules
4.0K    ./ghost.bak/package.json
4.0K    ./ghost.bak/PRIVACY.md
8.0K    ./ghost.bak/README.md
4.0K    ./ghost.bak/SECURITY.md
1.2M    ./ghost.bak/yarn.lock
```

The `.cache/yarn` directory still takes quite a lot but after emptying it, there is a great improvement!

```
root@nicofrand:/var/www# du -sh ./ghost/.cache/*
7.2M    ./ghost/.cache/node-gyp
548M    ./ghost/.cache/yarn
```

**Comment by nicofrand** [comment]
https://github.com/YunoHost-Apps/ghost_ynh/pull/209 would be great in addition (I deleted the branch by mistake but you can see the diff)

**Comment by tituspijean** [comment]
Done!
