### ISSUE TITLE
Unable to upload post or page image

### ISSUE THREAD

**Issue by addictif80** [YunoHost-Apps/ghost_ynh#20]
Hi everybody,
first, i'm sorry for my english, but i'm french.

I've recently installed YunoHost on a classic computer (i5, 8GB of RAM) and Debian.
I've migrate my old Ghost installation (export functionnality in "Labs" on admin panel) to the YunoHost fresh install.

All is ok, my posts are availables and the old images are here.
But, when i create a new post, i upload an image, but when i go to the published article, my image doesn't show, i just see a brocken image icon, and if i go to the absolute image URL, i have an error 500.
You can test : https://blog.abhd.fr/content/images/size/w2000/2020/01/epidemie_coronavirus_2019_ncov_chine.jpg

"EACCES: permission denied, mkdir '/var/www/ghost/content/images/size/w2000/2020/01'"

The folder "Content" in /var/www/ghost/ have this permission 
drwxr-xr-x    8 ghost ghost   4096 janv. 14 09:22 content

The "images" folder have this permission
drwxr-xr-x 5 ghost ghost 4096 janv. 25 13:36 images

They folders in "images" folder have this permission
drwxr-xr-x 4 ghost ghost 4096 janv. 19 20:52 2019
drwxr-xr-x 3 ghost ghost 4096 janv. 25 13:36 2020
-rw-r--r-- 1 ghost ghost   99 janv. 14 09:04 README.md
drwxr-xr-x 8 ghost ghost 4096 janv. 19 20:52 size

If you have any idea, i'm here, because i realy would like to use YunoHost for my production.
Best regards, Addictif80

**Comment by anmol26s** [comment]
Can someone test this branch and see if the issue is fixed?

`$ yunohost app install --debug https://github.com/YunoHost-Apps/ghost_ynh/tree/admin-fix `

**Comment by guyjames** [comment]
I have exactly the same issue and have tried the command above to install the admin-fix version but it is still giving the 502 error. I am being notified that v4 of Ghost is out now, so maybe updating the YH version to that will solve the problem?

**Comment by tituspijean** [comment]
Looks like it is solved now. Feel free to reopen if needed.
