### ISSUE TITLE
Upload Limit 

### ISSUE THREAD

**Issue by thelaserguy** [YunoHost-Apps/ghost_ynh#232]
# Describe the bug
When trying to import a large WordPress file into Ghost on YunoHost, the file size exceeds the allowed limit. Editing the client_max_body_size in the /etc/yunohost/apps/ghost/conf/nginx.conf file does not solve the issue.

## Context

- Hardware: Out of lease enterprise Lenovo i5 
- YunoHost version: 11.1.18 (stable)
- I have access to my server: direct, ssh, web portal 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: Installed version: 5.44.0~ynh1
- If upgrading, current package version: new installation

## Steps to reproduce

1. Install Ghost on YunoHost
2. Export WordPress content using the Ghost plugin for WordPress
3. Attempt to import the exported WordPress file into Ghost on YunoHost
4. Encounter error due to file size being too large
5. Edit /etc/yunohost/apps/ghost/conf/nginx.conf and change client_max_body_size from 100M to 500M
6. Restart nginx with sudo service nginx restart
7. Try importing the file again, but the issue persists

## Expected behavior

After increasing the client_max_body_size and restarting nginx, the larger WordPress file should be able to be imported into Ghost without any issues.

## Logs
Couldn't find any relevant data, no other error populating

**Comment by borisnoyet** [comment]
Hello, 
Have you tried to instead edit : /etc/nginx/conf.d/yourdomain.tld.d/ghost.conf ?
Yunohost uses specific per domain nginx config files. I'm not sure the /etc/yunohost/apps/ghost/conf/nginx.conf has the priority for the web server

**Comment by tituspijean** [comment]
Indeed. `/etc/yunohost/apps` contains a copy of each apps packages, the actual NGINX conf files are deployed where @borisnoyet stated.
