### ISSUE TITLE
Upgrade from 5.60.0~ynh1 to 5.60.0~ynh2 worked but 502 Gateway

### ISSUE THREAD

**Issue by borisnoyet** [YunoHost-Apps/ghost_ynh#245]
### Describe the bug

*Made updates via the webadmin for both websites (/var/www/ghost and /var/www/ghost__2). Upgrades seems to work fine but finally the sites display 502 Bad gateway*
*Nginx configs look fine in /etc/nginx/conf.d/*
*Was able to restore the backups to 5.60.0~ynh1 and back to normal for both websites*

### Context

- Hardware: *Mini PC machine*
- YunoHost version: *11.2.4*
- I have access to my server: *Through SSH + through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce

- *If you used the webadmin, please perform the equivalent command from the CLI first.*
- *Simple update from 5.60.0\~ynh1 to 5.60.0\~ynh2*

### Logs
Here are the two logs (for each website) : 

https://paste.yunohost.org/raw/kavatagale
https://paste.yunohost.org/raw/ojahuwazal

**Comment by borisnoyet** [comment]
That was that ; the host line in database section of `config.production.json` was `localhost` instead of `127.0.0.1`
Then the update ran fine on both ghost instances. Thank you !

**Comment by tituspijean** [comment]
Great, but I don't understand why it was not set correctly during the upgrade, the code states `127.0.0.1`.

**Comment by tituspijean** [comment]
Should have been fixed by 7419e559ac06f8e18f9a0645195132582bf49b61

**Comment by borisnoyet** [comment]
Yes, I confirm. Rolled back 5.60.0\~ynh1 from a backup then applied 5.61.2\~ynh2. Upgrade worked perfectly 👌
