### ISSUE TITLE
Using "ghost-cli" how-to ?? Installed OK but I can't use it

### ISSUE THREAD

**Issue by kalak-sudo** [YunoHost-Apps/ghost_ynh#26]
Yunohost version: 4.0.8.3 (stable)
Ghost version: 3.19.2~ynh1
VPS: Debian 10 64 bits

I typed:

`sudo npm install -g ghost-cli@latest`

Everything perfect. Now, when I type for example "ghost update" on the folder where Ghost was installed by Yunohost, it says there is no Ghost installation there:

> 
> Ghost-CLI commands do not work inside of a git clone, zip download or with Ghost <1.0.0.
> Perhaps you meant `grunt update`?
> Otherwise, run `ghost update` again within a valid Ghost installation.

Where is installed so I can use "ghost-cli"? 

Thanks!

**Comment by anmol26s** [comment]
The app is installed under the directory **/var/www/ghost**

**Comment by tituspijean** [comment]
As stated in the first line of the error, `Ghost-CLI commands do not work inside of a git clone, zip download or with Ghost <1.0.0.`. This package is installed from a zip download.
