### ISSUE TITLE
No Edit Panel after Ghost Install 

### ISSUE THREAD

**Issue by jlopez777** [YunoHost-Apps/ghost_ynh#28]
**Describe the bug**
No admin / edit page listed after install - just ghost "starter" posts. 

**Versions**

- Hardware:  Old laptop 
- 
- YunoHost version: Powered by YunoHost 4.0.8.3 (stable).
- 
- I have access to my server: Through the webadmin 
- 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: 
- No

**To Reproduce**
Ghost 3.19.2~ynh1

- *If the error occurs in your browser, explain what you did:*
   1. Install Ghost via webadmin. (see logs image1)
   2. Click to launch
   3. No error message - just missing edit panel (see image2 of working image from ghost.org free trial I used to get image)
   4. See image3 - what I actually see. 

When I try to mirror the working links in the ghost.org normal account (not my yunohost self hosted version), I DON'T get an error message or 404 message. 

e.g. https://mydomain.nohost.me/ghost/#/site ---> page remains the same as if I successfully went there, but it just keeps me at the normal "getting started" landing page. 

**Expected behavior**
I expected to see edit panel on left. 

**Logs**
image1
![image](https://user-images.githubusercontent.com/24819585/103258966-57e3bf00-4965-11eb-855b-4b45b9f8d6c0.png)

image2
missing section - the edit/admin panel on left taken from ghost.org free trial, what I expect to see in yellow. 
![image](https://user-images.githubusercontent.com/24819585/103258995-7cd83200-4965-11eb-8246-4cc3e2437cc9.png)

image3
what I see via yunhost ghost 
![image](https://user-images.githubusercontent.com/24819585/103259263-97f77180-4966-11eb-95ce-20733352a249.png)

**Comment by daveyultra** [comment]
I'm having the same exact issue - some guidance, or a response - would be nice.

On a separate note, I will probably be releasing my own version - not forked. Stand by.

**Comment by jlopez777** [comment]
> I'm having the same exact issue - some guidance, or a response - would be nice.

I spoke with one of the maintainers, he issued an update, but I don't think the update was targeted to fix this yet. Hopefully this upcoming weekend he can have a specific fix for this.

**Comment by anmol26s** [comment]
Can someone test this branch and see if the issue is fixed?

`$ yunohost app install --debug https://github.com/YunoHost-Apps/ghost_ynh/tree/admin-fix `

**Comment by jlopez777** [comment]
Going to try out now.

**Comment by jlopez777** [comment]
![image](https://user-images.githubusercontent.com/24819585/109094932-c97f8580-76e8-11eb-8830-966f5a966e72.png)


update - so far so good, just a few warnings...not sure what they mean since I'm not a web-dev.

**Comment by jlopez777** [comment]
We are getting some where. In the documentation - we need to add that to access admin panel, one must add /ghost at end of /blog. 

or make that the first page upon first launch. 
![image](https://user-images.githubusercontent.com/24819585/109095743-52e38780-76ea-11eb-8117-f0543c6041d8.png)

**Comment by jlopez777** [comment]
In the "create yuor account" screen, I created my account, but got an error. When I tried again, it said in top right corner of that screen "user already created" but still gave me the "athorization head format is "authorization: Ghost [token]. 

I decide to go back to ...nohost.me/blog/ghost and I get this when trying to sign in with the account I just created. 
![image](https://user-images.githubusercontent.com/24819585/109096146-00569b00-76eb-11eb-8296-be1944596ccc.png)

I try my yunohost credentials, but it gives me an error saying user hasn't been created yet.

**Comment by jlopez777** [comment]
Clicking on forget to see if I can get "registered" that way but get loading circle and nothing happening. 

Def. a step in the right direction! We are close! 

![image](https://user-images.githubusercontent.com/24819585/109096452-8d99ef80-76eb-11eb-9b1e-d973e50b4444.png)

**Comment by anmol26s** [comment]
This problem is not related to Yunohost. See here:
https://forum.ghost.org/t/authorization-header-format-is-authorization-ghost-token/9448
If the app is installed in public mode, it would work as expected. A fix would be to keep the /ghost path outside the private part. But this would give access to the admin interface for the Ghost to anyone, thus defeating the whole purpose of keeping the app private.

**Comment by jlopez777** [comment]
I checked off the check box when asked if this app would be exposed to
anonymous visitors.

The check mark needs language to describe explicitly what that implies.

There is no distinction made between having app admin page public or having
entire app public only except admin page  private vs having everything
private (subscribers have to sign up w ghost account to view posts).

Ill reinstall with it private but I'm pretty sure I tried that.

**Comment by jlopez777** [comment]
Oddly enough, I put my computer in hibernate mode, open it up today - and presto - I see admin panel and ability to edit posts....I guess it needed a few minutes to sort out any session token issues? Idk. 

![image](https://user-images.githubusercontent.com/24819585/109390935-8557d500-78e2-11eb-8195-6a641beecd98.png)

**Comment by jlopez777** [comment]
So to confirm, i installed in public mode, and either it needs time to reset, refresh, who knows...but eventually it recognized my login. 

I was able to successfully logout and log back in so its officially working! thank you @anmol26s ! I've been telling people about the project and especially the benefits of ghost over wordpress for non techy writers.

**Comment by anmol26s** [comment]
I have forced the /ghost part of the path to be out of the private path. But I don't know why would one keep a blogging platform like Ghost private? 
Anyways this will fix the header error as well.

**Comment by jlopez777** [comment]
I think they have a subscriber mode, where "followers" have to login to
view.
