### ISSUE TITLE
Unused ghost install produces lots of log data (22Go!)

### ISSUE THREAD

**Issue by arthurlogilab** [YunoHost-Apps/ghost_ynh#34]
**How to post a meaningful bug report**
1. *Read this whole template first.*
2. *Determine if you are on the right place:*
   - *If you were performing an action on the app from the webadmin or the CLI (install, update, backup, restore, change url...), you are on the right place!*
   - *Otherwise, the issue may be due to Ghost itself. Refer to its documentation or repository for help.*
   - *If you have a doubt, post here, we will figure it out together.*
3. *Delete the italic comments as you write over them below, and remove this guide.*
--- 

**Describe the bug**
On a test server we installed ghost, which in the end we haven't been using, and it's filling up the disk with log files

![Screenshot from 2021-02-11 10-16-11](https://user-images.githubusercontent.com/445200/107618880-90f49c00-6c52-11eb-9221-73e80ce4c3f3.png)

![Screenshot from 2021-02-11 10-16-34](https://user-images.githubusercontent.com/445200/107618895-95b95000-6c52-11eb-97e3-b7966e388828.png)

**Versions**
- Hardware: VM
- YunoHost version: Powered by YunoHost 4.1.7.1 (stable).
- I have access to my server: *Through SSH | through the webadmin.*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: *yes*
  - If yes, please explain: lots of test applications

**Comment by anmol26s** [comment]
I don't use Ghost, but what are these logs? Maybe logrotate on these would be required.

**Comment by tituspijean** [comment]
@arthurlogilab It looks like an issue from upstream. Have you seen [this thread on Ghost's forum](https://forum.ghost.org/t/rules-regarding-cleanup-of-json-files-in-content-data/19628)? You should check for any upgrade issues, because you have a file every 5 seconds, which looks like a failing automated process.

**Comment by tituspijean** [comment]
Let's close for the time being. Maybe we could add this path to `logrotate` to delete older backups if the problem arises again?
