### ISSUE TITLE
You are trying to install Ghost v5.89.1, which has been deprecated with the following notice: "Bug with editor only saving new drafts if the title is populated"

### ISSUE THREAD

**Issue by Lezney** [YunoHost-Apps/ghost_ynh#374]
### Describe the bug

Install fails

### Context

- Hardware: N100 Mini PC
- YunoHost version: 11.2.27
- I have access to my server:  through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 5.89.1

### Steps to reproduce

Click install button in Web UI

### Logs

https://paste.yunohost.org/raw/nowifiwodi

**Comment by aligitor** [comment]
Same here. I also have access through ssh, but installing from cli with -f option gives the same error and aborts the installation. Is it possible to install an earlier version of Ghost?

**Comment by tituspijean** [comment]
Fixed by #375

**Comment by blahajgoblin** [comment]
@tituspijean Do you think you'd be able to merge the https://github.com/YunoHost-Apps/ghost_ynh/tree/ci-auto-update-5.110.1 branch? 
https://www.npmjs.com/package/ghost?activeTab=versions Since this PR, Ghost published a new version which blocks users from installing it right now.

**Comment by tituspijean** [comment]
Done by yalh in #438.
It's better to open a new issue or ping us in the support chat rooms, since this issue is 6 months old and already closed. 😉
