### ISSUE TITLE
Upgrade to 4.15.1 to patch security vulnerabliity 

### ISSUE THREAD

**Issue by badrihippo** [YunoHost-Apps/ghost_ynh#48]
### Security vulnerability

Ghost has found and fixed a breach that allowed unauthenticated email users to change the email addresses of arbitrary member accounts. Details can be found [here](https://github.com/TryGhost/Ghost/security/advisories/GHSA-65p7-pjj8-ggmr).

### Affected versions

The vulnerability affects Ghost versions between 3.18.0 and 4.15.0 (inclusive), which includes the version of Ghost used in this repo (4.9.1). We should upgrade this to the patched version, 4.15.1, as soon as possible so that YunoHost users can be protected too.

### Solutions

Upgrade to the patched version of Ghost, 4.15.1

**As a temporary measure:** before upgrading, one can block the `POST /members/api/send-magic-link/` endpoint—but this is not recommended as it would also block legitimate members from logging in and signing up on the site. I'm not very good at nginx configuration, but if someone could paste instructions on how to do this, that would help!

**Comment by ericgaspar** [comment]
Fixed with #53
