### ISSUE TITLE
RPI2 = Minibian + YunoHost + Ghost = Bad Gateway 502

### ISSUE THREAD

**Issue by abacao** [YunoHost-Apps/ghost_ynh#6]
Hi there,

I've installed a YunoHost into my raspberry pi 2 and it's mostly working.

Tried to install Ghost, it says "Installation complete", the Ghost icon shows in the YunoHost but when I try to open it, I get a 502 Bad Gateway.

How can I help to sort this out?

**Comment by julienmalik** [comment]
duplicate of #8 
this app needs love from a new maintainer.
