### ISSUE TITLE
I can't install Ghost

### ISSUE THREAD

**Issue by Sysdraw** [YunoHost-Apps/ghost_ynh#99]
### Describe the bug

When I going in my website after installed, I have the error message "502 Bad Gateway".

### Context

- Hardware: *VPS*
- YunoHost version: *4.3.5*
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: *master*
### Steps to reproduce
```sh
    sudo yunohost app install ghost
```
### Expected behavior

After the setup, I have a database "ghost", but I have nothing inside...

### Logs

https://paste.yunohost.org/pajekosoju

**Comment by tituspijean** [comment]
Man, you are really unlucky with your server so far. 😓 
Can you have a look to this? https://stackoverflow.com/questions/46140902/protocol-packets-out-of-order
`500M` may be too high, try increasing the value. You will need to restart the mysql service.

**Comment by Sysdraw** [comment]
I tried but same error...

**Comment by tituspijean** [comment]
FYI I can replicate the issue now.

**Comment by tituspijean** [comment]
Should be solved now.
